name: Quality check

on:
  push:
    branches:
      - master

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache node_modules
        id: cache-admin
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-admin.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lock

      - name: Run ESlint
        run: |
          yarn lint

      - name: Run Type check
        run: |
          yarn typecheck

      - name: Run Prettier check
        run: |
          yarn format:check
